export const ARTICULO_GET = 'ARTICULO_GET'; 
export const ARTICULO_DELETE = 'ARTICULO_DELETE'; 
export const ARTICULO_FIND = 'ARTICULO_FIND';  
export const ARTICULO_UPDATE = 'ARTICULO_UPDATE'; 
export const ARTICULO_EMPTY = 'ARTICULO_EMPTY';  
export const ARTICULO_CREATE = 'ARTICULO_CREATE'; 
export const ARTICULO_CLEAR = 'ARTICULO_CLEAR'; 

