export const ARTICULO_GET = 'ARTICULO_GET';  
export const ARTICULO_FIND = 'ARTICULO_FIND';  
export const ARTICULO_UPDATE = 'ARTICULO_UPDATE'; 
export const ARTICULO_EMPTY = 'ARTICULO_EMPTY';   

export const ARTICULO_SOLICITUD = 'ARTICULO_SOLICITUD';
export const ARTICULO_CREATE = 'ARTICULO_CREATE';
export const ARTICULO_RESPONSE = 'ARTICULO_RESPONSE'; 
export const ARTICULO_ERROR = 'ARTICULO_ERROR'; 
export const ARTICULO_VOID = 'ARTICULO_VOID'; 


export const ARTICULO_CREATE_SOLICITUD  = 'ARTICULO_CREATE_SOLICITUD';
export const ARTICULO_CREATE_EJECUCION = 'ARTICULO_CREATE_EJECUCION';
export const ARTICULO_CREATE_RESPONSE = 'ARTICULO_CREATE_RESPONSE'; 


export const ARTICULO_DELETE_SOLICITUD = 'ARTICULO_DELETE_SOLICITUD';
export const ARTICULO_DELETE_EJECUCION = 'ARTICULO_DELETE_EJECUCION';
export const ARTICULO_DELETE_RESPONSE = 'ARTICULO_DELETE_RESPONSE';
export const ARTICULO_DELETE_VOID = 'ARTICULO_DELETE_VOID';